import type { Request, Response, NextFunction } from "express";
import jwt from "jsonwebtoken";
import { User } from "../models/user.model.js";
import type { RequestWithUser } from "../controllers/user.controller.js";
import { School } from "../models/School.model.js";
import { Teacher } from "../models/teacher.model.js";
import { Student } from "../models/student.model.js";

interface JwtDecoded {
    id: string;
    iat: number;
    exp: number;
    role: "admin" | "school" | "teacher" | "student";
}

export const verifyJwt = async (req: RequestWithUser, res: Response, next: NextFunction) => {
    try {
        const token = req.cookies?.token;
        if (!token) {
            return res.status(401).json({ success: false, message: "No token provided" });
        }
        // console.log("Token is generated by auth: ",token);

        const decoded = jwt.verify(token, process.env.JWT_SECRET!) as JwtDecoded;
        // console.log("Decoded: ",decoded);
        const { id,role } = decoded;

        let user : any =null;

        if (role === "admin") {
            user = await User.findById(id).select("-password");
        }

        if(role === "school") {
            user = await School.findById(id).select("-password");
        }

        if(role === "teacher") {
            user = await Teacher.findById(id).select("-password");
        }

        // if(role === "student") {
        //     user = await Student.findById(id).select("-password");
        // }

        if (!user) {
            return res.status(401).json({ success: false, message: "User not found" });
        }

        req.user = {
            _id: user._id.toString(),
            email: user.email,
            role: role,
        };

        next();
    } catch (error) {
        console.error("JWT verification error:", error);
        return res.status(401).json({ success: false, message: "Unauthorized" });
    }
};
